import fs from 'fs'

export const products: any [] = [
  {
    id: '1',
    name: 'Pretty Love Snappy',
    imageUrl: fs.readFileSync(`./img/prettylovesnappy.jpg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'Add rice and stir very gently to distribute. Top with artichokes and',
  },
  {
    id: '2',
    name: 'Screaming Bullet',
    imageUrl: fs.readFileSync(`./img/screamingbullet.jpg`, 'base64'),
    price: 200,
    favorite: true,
    stars: 4,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',
  },
  {
    id: '3',
    name: 'Mini Love Eggs',
    imageUrl: fs.readFileSync(`./img/miniloveeggs.jpg`, 'base64'),
    favorite: false,
    stars: 3,
    price: 390,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',

  },
  {
    id: '4',
    name: 'Mouth Mastibator',
    imageUrl: fs.readFileSync(`./img/mouthmasturbator.jpg`, 'base64'),
    price: 350,
    favorite: false,
    stars: 4,
    description: '15 to 18 minutes. Reduce heat to medium-low, add reserved shrimp and',
  },
  {
    id: '5',
    name: 'Pretty Love Adonis',
    imageUrl: fs.readFileSync(`./img/prettyloveadonis.jpg`, 'base64'),
    price: 300,
    favorite: true,
    stars: 4,
    description: ' mussels, tucking them down into the rice, and cook again without',
  },
  {
    id: '6',
    name: 'Pretty Love Eudora',
    imageUrl: fs.readFileSync(`./img/prettyloveeudora.jpg`, 'base64'),
    price: 300,
    favorite: true,
    stars: 4,
    description: 'stirring, until mussels have opened and rice is just tender, 5 to 7',
  },
  {
    id: '7',
    name: '4cm Pleasure Ball',
    imageUrl: fs.readFileSync(`./img/4cmballs.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Bradley',
    imageUrl: fs.readFileSync(`./img/prettylovebradley.jpg`, 'base64'),
    price: 450,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Mini Pink: Body Wand',
    imageUrl: fs.readFileSync(`./img/bodywand.jpg`, 'base64'),
    price: 580,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Purple',
    imageUrl: fs.readFileSync(`./img/purplefunction.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Baile Jessica Strapp-on set',
    imageUrl: fs.readFileSync(`./img/BaileJessicastrapp.jpg`, 'base64'),
    price: 350,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Clit Pump',
    imageUrl: fs.readFileSync(`./img/clitpump.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Dong',
    imageUrl: fs.readFileSync(`./img/dong.jpg`, 'base64'),
    price: 500,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Lace Hand Cuffs',
    imageUrl: fs.readFileSync(`./img/lacecuffs.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Adjustable Leather Hand Cuffs',
    imageUrl: fs.readFileSync(`./img/leathercuffs.jpg`, 'base64'),
    price: 180,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Love Peter',
    imageUrl: fs.readFileSync(`./img/lovepeter.jpg`, 'base64'),
    price: 400,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Brighty',
    imageUrl: fs.readFileSync(`./img/prettylovebrighty.jpg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Daniel',
    imageUrl: fs.readFileSync(`./img/prettylovedaniel.jpg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Nylon Detail Hand-Cuffs',
    imageUrl: fs.readFileSync(`./img/NylonCuffs.jpg`, 'base64'),
    price: 220,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Betram',
    imageUrl: fs.readFileSync(`./img/prettylovebetram.jpg`, 'base64'),
    price: 250,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Gladys',
    imageUrl: fs.readFileSync(`./img/prettylovegladys.jpg`, 'base64'),
    price: 650,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Pretty Love Steve',
    imageUrl: fs.readFileSync(`./img/prettylovesteve.jpg`, 'base64'),
    price: 300,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Vibra Butt Plug',
    imageUrl: fs.readFileSync(`./img/vibrabutplug.jpg`, 'base64'),
    price: 350,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    id: '7',
    name: 'Vibratone Balls',
    imageUrl: fs.readFileSync(`./img/vibratonebalss.jpg`, 'base64'),
    price: 150,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
]


export const users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: true
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: false
  },
]