import fs from 'fs'

export const products: any [] = [
  {
    name: 'Pxya',
    imageUrl: fs.readFileSync(`./img/1.jpeg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'Add rice and stir very gently to distribute. Top with artichokes and',
  },
  {
    name: 'Sxyb',
    imageUrl: fs.readFileSync(`./img/2.jpg`, 'base64'),
    price: 200,
    favorite: true,
    stars: 4,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',
  },
  {
    name: 'Mxyc',
    imageUrl: fs.readFileSync(`./img/3.jpg`, 'base64'),
    favorite: false,
    stars: 3,
    price: 390,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',

  },
  {
    name: 'Mxyd',
    imageUrl: fs.readFileSync(`./img/4.jpg`, 'base64'),
    price: 350,
    favorite: false,
    stars: 4,
    description: '15 to 18 minutes. Reduce heat to medium-low, add reserved shrimp and',
  },
  {
    name: 'Pxye',
    imageUrl: fs.readFileSync(`./img/4.jpg`, 'base64'),
    price: 300,
    favorite: true,
    stars: 4,
    description: ' mussels, tucking them down into the rice, and cook again without',
  },
  {
    name: 'Pxyf',
    imageUrl: fs.readFileSync(`./img/5.jpg`, 'base64'),
    price: 300,
    favorite: true,
    stars: 4,
    description: 'stirring, until mussels have opened and rice is just tender, 5 to 7',
  },
  {
    name: 'Mxyg',
    imageUrl: fs.readFileSync(`./img/6.jpeg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Pxyh',
    imageUrl: fs.readFileSync(`./img/7.webp`, 'base64'),
    price: 450,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyj',
    imageUrl: fs.readFileSync(`./img/8.jpeg`, 'base64'),
    price: 580,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyi',
    imageUrl: fs.readFileSync(`./img/9.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyk',
    imageUrl: fs.readFileSync(`./img/10.jpeg`, 'base64'),
    price: 350,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyl',
    imageUrl: fs.readFileSync(`./img/11.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxym',
    imageUrl: fs.readFileSync(`./img/12.jpeg`, 'base64'),
    price: 500,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyn',
    imageUrl: fs.readFileSync(`./img/12.jpg`, 'base64'),
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyo',
    imageUrl: fs.readFileSync(`./img/13.jpg`, 'base64'),
    price: 180,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyp',
    imageUrl: fs.readFileSync(`./img/14.jpg`, 'base64'),
    price: 400,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyq',
    imageUrl: fs.readFileSync(`./img/15.jpeg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyr',
    imageUrl: fs.readFileSync(`./img/16.jpeg`, 'base64'),
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxys',
    imageUrl: fs.readFileSync(`./img/17.jpg`, 'base64'),
    price: 220,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyt',
    imageUrl: fs.readFileSync(`./img/18.jpeg`, 'base64'),
    price: 250,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyuuz',
    imageUrl: fs.readFileSync(`./img/19.jpg`, 'base64'),
    price: 650,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Pretty Love Steve',
    imageUrl: fs.readFileSync(`./img/20.webp`, 'base64'),
    price: 300,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  }
]


export const users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: true
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: false
  },
]
