import { Products } from './app/shared/models/Products'

export const products: Products [] = [
  {
    id: '1',
    name: 'Designer Brand one',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/cleanarchitecture.jpg',
    price: 20.98,
    tags:"",
    favorite: false,
    stars: 4,
    description: 'Add rice and stir very gently to distribute. Top with artichokes and',
  },
  {
    id: '2',
    name: 'Product 2',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/cleancode.jpg',
    price: 32.98,
    tags:"",
    favorite: true,
    stars: 4,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',
  },
  {
    id: '3',
    name: 'Product 3',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/imac1.jpg',
    tags: "",
    favorite: false,
    stars: 3,
    price: 4206.9,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',

  },
  {
    id: '4',
    name: 'Product 4',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/keyboard1.jpg',
    price: 99.98,
    tags:"",
    favorite: false,
    stars: 4,
    description: '15 to 18 minutes. Reduce heat to medium-low, add reserved shrimp and',
  },
  {
    id: '5',
    name: 'No no no',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/keyboard2.jpg',
    price: 99.98,
    tags:"",
    favorite: true,
    stars: 4,
    description: '                            mussels, tucking them down into the rice, and cook again without',
  },
  {
    id: '6',
    name: 'Yes 10',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/mouse1.jpg',
    price: 99.98,
    tags:"",
    favorite: true,
    stars: 4,
    description: '                            stirring, until mussels have opened and rice is just tender, 5 to 7',
  },
  {
    id: '7',
    name: 'Designer Brand',
    imageUrl: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/products/mouse2.jpg',
    price: 99.98,
    tags:"",
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
]
