export const products: any [] = [
  {
    name: 'Pxya',
    imageUrl: `./img/1.jpeg`,
    price: 400,
    favorite: false,
    stars: 4,
    description: 'Add rice and stir very gently to distribute. Top with artichokes and',
  },
  {
    name: 'Sxyb',
    imageUrl: `./img/2.jpg`,
    price: 200,
    favorite: true,
    stars: 4,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',
  },
  {
    name: 'Mxyc',
    imageUrl: `./img/3.jpg`,
    favorite: false,
    stars: 3,
    price: 390,
    description: 'peppers, and cook without stirring, until most of the liquid is absorbed,',

  },
  {
    name: 'Mxyd',
    imageUrl: `./img/4.jpg`,
    price: 350,
    favorite: false,
    stars: 4,
    description: '15 to 18 minutes. Reduce heat to medium-low, add reserved shrimp and',
  },
  {
    name: 'Pxye',
    imageUrl: `./img/4.jpg`,
    price: 300,
    favorite: true,
    stars: 4,
    description: ' mussels, tucking them down into the rice, and cook again without',
  },
  {
    name: 'Pxyf',
    imageUrl: `./img/5.jpg`,
    price: 300,
    favorite: true,
    stars: 4,
    description: 'stirring, until mussels have opened and rice is just tender, 5 to 7',
  },
  {
    name: 'Mxyg',
    imageUrl: `./img/6.jpeg`,
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Pxyh',
    imageUrl: `./img/7.webp`,
    price: 450,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyj',
    imageUrl: `./img/8.jpeg`,
    price: 580,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyi',
    imageUrl: `./img/9.jpg`,
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyk',
    imageUrl: `./img/10.jpeg`,
    price: 350,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyl',
    imageUrl: `./img/11.jpg`,
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxym',
    imageUrl: `./img/12.jpeg`,
    price: 500,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyn',
    imageUrl: `./img/12.jpg`,
    price: 150,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyo',
    imageUrl: `./img/13.jpg`,
    price: 180,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyp',
    imageUrl: `./img/14.jpg`,
    price: 400,
    favorite: true,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyq',
    imageUrl: `./img/15.jpeg`,
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyr',
    imageUrl: `./img/16.jpeg`,
    price: 400,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxys',
    imageUrl: `./img/17.jpg`,
    price: 220,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyt',
    imageUrl: `./img/18.jpeg`,
    price: 250,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Mxyuuz',
    imageUrl: `./img/19.jpg`,
    price: 650,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  },
  {
    name: 'Pretty Love Steve',
    imageUrl: `./img/20.webp`,
    price: 300,
    favorite: false,
    stars: 4,
    description: 'minutes more. (Discard any mussels that dont open.',
  }
]


export const users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: true
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Cape Town",
    isAdmin: false
  },
]
